### ISSUE TITLE
My sword isn't gonna work

### ISSUE THREAD

**Issue by Pippa015** [srnyx/geeksmp-rp#1]
### Expected behavior

The name of a PNG and the given file in the . properties (texture=*****.png) should be the same 

### Actual behavior

In my sword, (location given in "steps to reproduce") the file name of the .PNG and the actual file name in the . properties, don't match, so the sword will not have it's texture when renamed.

### Steps to reproduce

Go to /pack/assets/minecraft/opticien/cit/pippa/nature_sword and open  nature_sword.properties. You will see that there will be "texture=green_sword". That is supposed to be "nature_sword".

### Version

I didn't play with it yet, just noticed it in the files.

### Checks

- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by srnyx** [comment]
Oh, sorry, must've forgotten to change it.
Next time you can just create a PR to fix it.
